steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_LOCATION-docker.pkg.dev/$_PROJECT/$_REPO/jhw:$COMMIT_SHA', '.' ]
images:
- '$_LOCATION-docker.pkg.dev/$_PROJECT/$_REPO/jhw:$COMMIT_SHA'