steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        tokres=$(curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" --header "Metadata-Flavor: Google");\
        echo Full token: $tokres;\
        token=$(echo $tokres | jq -r '.access_token');\
        echo Short token: $token;\
        res=$(curl -H "Authorization: Bearer $token" $_URI/hello-world);\
        if (echo $res | grep "Hello World"); then echo success; else echo ERROR: unexpected curl result. Token: $token, res: $res; exit 1; fi