steps:
  - name: gcr.io/${_PROJECT}/curl
    entrypoint: bash
    args:
      - "-c"
      - |
        if (curl https://jhwtest-nfebyz4gja-uc.a.run.app/hello-world | grep hw); then echo success; else echo ERROR: unexpected curl result; exit 1; fi