steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        if (curl https://jhwtest-nfebyz4gja-uc.a.run.app/hello-world | grep "Hello World"); then echo success; else echo ERROR: unexpected curl result; exit 1; fi