steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud workflows execute ci_example --project=$_WF_PROJECT --location=$_WF_LOCATION --data={\"sha\":\"$COMMIT_SHA\",\ \"location\":\"$LOCATION\"}