steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud workflows execute ci-example --project=$_WF_PROJECT --location=$_WF_LOCATION --data="{\"sha\":\"$COMMIT_SHA\", \"location\":\"$_LOCATION\", \"project\":\"$_PROJECT\", \"repo\":\"$_REPO\"}"