steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - workflows
    - execute
    - ci_example
    - --location="$_WF_LOCATION"
    - --project="$_WF_PROJECT"
    - --data="{\"sha\":\"$COMMIT_SHA\", \"location\":\"$LOCATION\"}"